Set the ARCH from command line or the system

diff --git a/ebootstrap b/ebootstrap
--- a/ebootstrap
+++ b/ebootstrap
@@ -62,6 +62,10 @@ while [[ "${1}" =~ ^-- ]]; do
         --bare)
             EBOOTSTRAP_BARE=1
             ;;
+        --arch)
+            ARCH=${2}
+            shift
+            ;;
         --help)
             usage --long
             exit 0
@@ -82,6 +86,16 @@ if [[ $# < ${__args} ]]; then
     usage
     exit -1
 fi
+
+# ensure that ARCH is valid
+# load it from the system if its not been explicitly defined
+# (this must be set before initialising the ebuild backend or its masked
+# by the PORTAGE_CONFIGROOT setting)
+: ${ARCH:="$(portageq envvar ARCH)"}
+if ! has "${ARCH}" amd64 x86; then
+    die "ERROR: invalid ARCH: ${ARCH}"
+fi
+export ARCH
 
 # load the backend
 if [[ -n "${EBOOTSTRAP_BACKEND}" ]]; then
